server:
  port: 8080  
spring:
  application:
    name: PARKING-LOT
    

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
 
 